# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07\x65xample\"\x1f\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1d\n\x0bPromptReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"I\n\x10GetAnswerRequest\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x11\n\tlanguages\x18\x02 \x03(\t\x12\x12\n\ncategories\x18\x03 \x03(\t\"#\n\x11GetAnswerResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"M\n\x15GetSuggestionsRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x11\n\tlanguages\x18\x02 \x03(\t\x12\x12\n\ncategories\x18\x03 \x03(\t\"-\n\x16GetSuggestionsResponse\x12\x13\n\x0bsuggestions\x18\x01 \x03(\t2\x95\x01\n\rPromptService\x12=\n\x0bGetResponse\x12\x16.example.PromptRequest\x1a\x14.example.PromptReply\"\x00\x12\x45\n\x11GetResponseStream\x12\x16.example.PromptRequest\x1a\x14.example.PromptReply\"\x00\x30\x01\x32\xe6\x02\n\x16\x44\x61tabaseHandlerService\x12Q\n\x0eGetSuggestions\x12\x1e.example.GetSuggestionsRequest\x1a\x1f.example.GetSuggestionsResponse\x12\x42\n\tGetAnswer\x12\x19.example.GetAnswerRequest\x1a\x1a.example.GetAnswerResponse\x12W\n\x14GetSuggestionsVector\x12\x1e.example.GetSuggestionsRequest\x1a\x1f.example.GetSuggestionsResponse\x12\\\n\x19GetSuggestionsVectorLocal\x12\x1e.example.GetSuggestionsRequest\x1a\x1f.example.GetSuggestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROMPTREQUEST']._serialized_start=26
  _globals['_PROMPTREQUEST']._serialized_end=57
  _globals['_PROMPTREPLY']._serialized_start=59
  _globals['_PROMPTREPLY']._serialized_end=88
  _globals['_GETANSWERREQUEST']._serialized_start=90
  _globals['_GETANSWERREQUEST']._serialized_end=163
  _globals['_GETANSWERRESPONSE']._serialized_start=165
  _globals['_GETANSWERRESPONSE']._serialized_end=200
  _globals['_GETSUGGESTIONSREQUEST']._serialized_start=202
  _globals['_GETSUGGESTIONSREQUEST']._serialized_end=279
  _globals['_GETSUGGESTIONSRESPONSE']._serialized_start=281
  _globals['_GETSUGGESTIONSRESPONSE']._serialized_end=326
  _globals['_PROMPTSERVICE']._serialized_start=329
  _globals['_PROMPTSERVICE']._serialized_end=478
  _globals['_DATABASEHANDLERSERVICE']._serialized_start=481
  _globals['_DATABASEHANDLERSERVICE']._serialized_end=839
# @@protoc_insertion_point(module_scope)
